---
# tasks file for rpx_nginx

- include_tasks: 01_variables.yml
- include_tasks: "10_setup-{{ ansible_facts.os_family }}.yml"
  when: rpx_role_execution != 'only_sites'
- include_tasks: 15_ssl_variables.yml

- name: Get nginx version.
  command:
    cmd: nginx -v
  register: _result_nginx_version
  changed_when: false
  ignore_errors: "{{ ansible_check_mode }}"
  check_mode: false  # run normally even in check mode

- name: Define _nginx_version.
  set_fact:
    _nginx_version: "{{ _result_nginx_version.stderr | regex_search('[0-9\\.]+') | default('1.30', true) }}"
    # `1.30` => a relatively recent default, to ensure functionality even in check mode.
    # Case distinctions based on the version should use/simulate a new configuration instead of an older one.

- block:
    - include_tasks: 20_configure.yml
    - include_tasks: 23_default_site.yml
    - include_tasks: 27_error_pages.yml
  when: rpx_role_execution != 'only_sites'

- name: Ensure nginx is started and enabled.
  service:
    name: nginx
    state: started
    enabled: yes

- include_tasks: 50_sites.yml
  when: rpx_role_execution != 'without_sites'
